//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBoom.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        private static DBEntities Context;
        public DBEntities()
            : base("name=DBEntities")
        {
        }
        public static DBEntities GetContext()
        {
            if (Context == null)
                Context = new DBEntities();
            return Context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cantri> Cantri { get; set; }
        public virtual DbSet<Cite> Cite { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Produkts> Produkts { get; set; }
        public virtual DbSet<Provader> Provader { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Strit> Strit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
