//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBoom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int IdInvoce { get; set; }
        public int IdProvider { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
    
        public virtual City City { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Street Street { get; set; }
    }
}
