//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBoom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkts
    {
        public int IdProdukt { get; set; }
        public string NameProdukt { get; set; }
        public int IdProvider { get; set; }
        public int Remains { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
