USE [master]
GO

/****** Object:  Database [Kur]    Script Date: 22.10.2022 0:35:52 ******/
CREATE DATABASE [Kur]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Kur', FILENAME = N'E:\SQLServer2017Media\MSSQL14.SQLEXPRESS02\MSSQL\DATA\Kur.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Kur_log', FILENAME = N'E:\SQLServer2017Media\MSSQL14.SQLEXPRESS02\MSSQL\DATA\Kur_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Kur].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Kur] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Kur] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Kur] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Kur] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Kur] SET ARITHABORT OFF 
GO

ALTER DATABASE [Kur] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Kur] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Kur] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Kur] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Kur] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Kur] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Kur] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Kur] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Kur] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Kur] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Kur] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Kur] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Kur] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Kur] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Kur] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Kur] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Kur] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Kur] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Kur] SET  MULTI_USER 
GO

ALTER DATABASE [Kur] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Kur] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Kur] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Kur] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Kur] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Kur] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Kur] SET  READ_WRITE 
GO

